# Default values for hetzner-dyndns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- cron schedule for refreshing dns entries
schedule: "*/15  * * * *"

# -- hetzner dns api token, see https://dns.hetzner.com/
apiToken: ""

image:
  repository: hashicorp/terraform
  pullPolicy: IfNotPresent
  tag: 1.3.7

helperImage:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: 3.17

terraformProviderVersions:
  # -- see https://registry.terraform.io/providers/hashicorp/http/
  http: 3.1.0
  # -- see https://registry.terraform.io/providers/timohirt/hetznerdns/
  hetznerdns: 2.2.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

domains:
  # -- DNS hosted zone and subdomains
  - name: "example.com"
    subdomains:
      # -- sets A Record for example.com
      - "@"
      # -- sets A Record for www.example.com
      - "www"
#  - name: "anotherexample.com"
#    subdomains: ["@", "www"]

persistence:
  storageClassName: local-path
  storageSize: 1Gi
  accessModes: ReadWriteOnce

nodeSelector: {}

tolerations: []

affinity: {}
