apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hetzner-dyndns.fullname" . }}-terraform-files
data:
  {{- $files := .Files }}
  {{- range $path, $_ := .Files.Glob "**/**.tf" }}
  {{ $path | replace "/" "_" }}: |
{{ $files.Get $path | indent 4 }}
  {{- end }}
#TODO add lock file
  {{- range $path, $_ := .Files.Glob "**/**.lock.hcl" }}
  {{ $path | replace "/" "_" }}: |
{{ $files.Get $path | indent 4 }}
  {{- end }}