apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hetzner-dyndns.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        {{- include "hetzner-dyndns.selectorLabels" . | nindent 8 }}
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: terraform-plan
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            workingDir: {{ .Values.persistence.mountPath }}
            command:
              - bash
            args:
              - -c
              - >
                cd {{ .Values.persistence.mountPath }} &&
                rm -rf *.tf &&
                cp /terraform-templates/*.tf . &&
                /terraform init &&
                /terraform apply -auto-approve
            volumeMounts:
              - mountPath: {{ .Values.persistence.mountPath }}
                name: {{ include "hetzner-dyndns.fullname" . }}-volume
              - mountPath: /terraform-templates
                name: {{ include "hetzner-dyndns.fullname" . }}-terraform-files
            env:
              - name: TF_VAR_hetznerdns_token
                valueFrom:
                  secretKeyRef:
                    name: {{ include "hetzner-dyndns.fullname" . }}
                    key: apiToken
                    optional: false
          volumes:
            - name: {{ include "hetzner-dyndns.fullname" . }}-volume
              persistentVolumeClaim:
                claimName: {{ include "hetzner-dyndns.fullname" . }}
            - configMap:
                name: {{ include "hetzner-dyndns.fullname" . }}-terraform-files
              name: {{ include "hetzner-dyndns.fullname" . }}-terraform-files
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
