apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hetzner-dyndns.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        {{- include "hetzner-dyndns.selectorLabels" . | nindent 8 }}
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: terraform-plan
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            workingDir: /terraform-dir
            command:
              - terraform
            args:
              - apply
              - -auto-approve
              - -lock=false
            volumeMounts:
              - mountPath: /terraform-dir
                name: {{ include "hetzner-dyndns.fullname" . }}-volume
            env:
              - name: TF_VAR_hetznerdns_token
                valueFrom:
                  secretKeyRef:
                    name: {{ include "hetzner-dyndns.fullname" . }}
                    key: apiToken
                    optional: false
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          volumes:
            - name: {{ include "hetzner-dyndns.fullname" . }}-volume
              persistentVolumeClaim:
                claimName: {{ include "hetzner-dyndns.fullname" . }}
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
