apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hetzner-dyndns.fullname" . }}-init-{{ include "hetzner-dyndns.configChecksum" . }}
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      initContainers:
        - name: setup-files
          image: "{{ .Values.helperImage.repository }}:{{ .Values.helperImage.tag }}"
          imagePullPolicy: {{ .Values.helperImage.pullPolicy }}
          workingDir: /terraform-dir
          command:
            - sh
          args:
            - -c
            - >
              cd /terraform-dir &&
              rm -rf *.tf &&
              cp /terraform-templates/*.tf .
          volumeMounts:
            - mountPath: /terraform-dir
              name: {{ include "hetzner-dyndns.fullname" . }}-volume
            - mountPath: /terraform-templates
              name: {{ include "hetzner-dyndns.fullname" . }}-terraform-files
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: terraform-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /terraform-dir
          command:
            - terraform
          args:
            - init
          volumeMounts:
            - mountPath: /terraform-dir
              name: {{ include "hetzner-dyndns.fullname" . }}-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "hetzner-dyndns.fullname" . }}-volume
          persistentVolumeClaim:
            claimName: {{ include "hetzner-dyndns.fullname" . }}
        - configMap:
            name: {{ include "hetzner-dyndns.fullname" . }}-terraform-files
          name: {{ include "hetzner-dyndns.fullname" . }}-terraform-files
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 0
