kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "hetzner-dyndns.fullname" . }}
  annotations:
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
