{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hetzner-dyndns.serviceAccountName" . }}
  labels:
    {{- include "hetzner-dyndns.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hetzner-dyndns.fullname" . }}
rules:
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
  - apiGroups: ["rbac.authorization.k8s.io",""]
    resources: ["namespaces"]
    verbs: ["get","list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hetzner-dyndns.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hetzner-dyndns.serviceAccountName" . }}
  apiGroup: ""
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ include "hetzner-dyndns.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}


